### ISSUE TITLE
Filename with "--useShortName" are ugly

### ISSUE THREAD

**Issue by wilfriedroset** [joaquinpf/manga_downloader#4]
When using "--useShortName" manga_downloader produce file named : <manga_name>.<space_token>.<chapter_number>.<ext>, for example: Onepunch-Man.-.088.cbz.

IMHO with this option filename would be prettier like this <manga_name><space_token><chapter_number>.<ext>, for example: Onepunch-Man-088.cbz.

It would make them easy to parse for android app (comicrack, Astonishing Comic Reader, ...)

**Comment by joaquinpf** [comment]
Hi! I just noticed it's not documented at all (my bad), but what you are looking for is most likely the --spaceToken switch, which defaults to '.'. So, if you want the tool to produce a cleaner name you could set it to --spaceToken ' ' (space character between quotes). That should output something like 'Onepunch-Man - 088.cbz'. I'm currently using ComicRack for Windows and Android without issue by setting it that way. Please let me know if that helps. Also, the 'develop' branch is currently quite ahead of 'master', could be useful depending on the provider you use (dropped some and added others).

**Comment by wilfriedroset** [comment]
Indeed the option does the trick.
